version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: >-
    nuget restore

    Copy-Item "packages\HtmlAgilityPack.1.11.12\lib\Net45\HtmlAgilityPack.dll" -Destination "TiComeOn\Include"

    Copy-Item "packages\Newtonsoft.Json.12.0.2\lib\net45\Newtonsoft.Json.dll" -Destination "TiComeOn\Include"
build:
  verbosity: minimal
artifacts:
- path: TiComeOn\bin\Release\TiCome.exe